# 应用程序配置文件
# 服务器配置
server:
  port: 8080
  servlet:
    context-path:
  tomcat:
    max-threads: 200
    min-spare-threads: 10
    connection-timeout: 30000

# 数据源配置
spring:
  application:
    name: provincial-node-service
  datasource:
    url: jdbc:mysql://192.168.4.212:3306/provincial_node?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: RE#xy=S&Z9
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  # Redis配置
  redis:
    host: 192.168.4.151
    port: 6379
    password: 123456
    database: 9
    timeout: 3000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1

# XXL-JOB配置
xxl:
  job:
    admin:
      addresses: http://192.168.4.151:9004/xxl-job-admin
    accessToken: default_token
    executor:
      appname: provincial-node-job
      logpath: logs/xxl-job/
      logretentiondays: 30
# 日志配置
logging:
  level:
    root: INFO
    com.example.provincialnode: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
  file:
    name: logs/provincial-node.log
    max-history: 30
    max-size: 10MB

# 自定义配置
provincial:
  node:
    # 全国节点配置
    national-node-url: http://national-node.example.com/api
    connect-timeout: 5000
    read-timeout: 10000
    # 令牌配置
    token:
      # 令牌有效期(秒)
      expire-time: 3600
      # 令牌刷新阈值(秒)
      refresh-threshold: 300
